# Generated by Django 6.0.6 on 2026-06-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selo',
            name='valor_centavos',
            field=models.IntegerField(default=0),
        ),
    ]
